package content

import "github.com/divijg19/Praxis/internal/challenge"

func All() []challenge.Challenge {
	return []challenge.Challenge{
		{
			ID:     "motion_rush",
			Name:   "Motion Rush",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Use h, j, k and l to move to the star ★",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "grid_rush",
			Name:   "Grid Rush",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Use h, j, k and l to move to the star ★",
				". . . . .",
				". . . ★ .",
				". . . . .",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "find_hunter",
			Name:   "Find Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Use f to jump to the next character",
				"",
				"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa★",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "word_hunter",
			Name:   "Word Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Use w to jump to the next word",
				"",
				"alpha beta gamma delta epsilon ★",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "symbol_hunter",
			Name:   "Symbol Hunter",
			Verify: "cursor",
			Target: "@",
			Content: []string{
				"Use f to find the target symbol",
				"",
				".......................@",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "line_hunter",
			Name:   "Line Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Use j and k to move to the line with the star",
				"",
				"line one",
				"line two",
				"line three",
				"line four",
				"line five",
				"★ line six",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "paren_hunter",
			Name:   "Paren Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Use % to jump to the matching parenthesis",
				"",
				"(                         )★",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "sentence_hunter",
			Name:   "Sentence Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Use ( and ) to jump between sentences",
				"",
				"First sentence ends here.",
				"Second. Third.",
				"★ Fourth. Fifth.",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "slash_hunter",
			Name:   "Slash Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Use / to search forward for the target",
				"",
				"alpha  bravo  charlie  delta  echo  foxtrot  golf  ★",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "question_hunter",
			Name:   "Question Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Use ? to search backward for the target",
				"",
				"line one",
				"line two",
				"line three",
				"line four",
				"line five",
				"line six",
				"line seven",
				"line eight",
				"line nine",
				"line ten",
				"line eleven",
				"line twelve",
				"line thirteen",
				"line fourteen",
				"line fifteen",
				"line sixteen",
				"★ line seventeen",
				"line eighteen",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "repeat_hunter",
			Name:   "Repeat Hunter",
			Verify: "cursor",
			Target: "@",
			Content: []string{
				"Use ; to repeat the last search",
				"",
				"★  ★  ★  ★  ★  ★  ★  ★  @",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "inner_paren_hunter",
			Name:   "Inner Paren Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Use i( to target inside the parentheses",
				"",
				"(hello★)",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "around_paren_hunter",
			Name:   "Around Paren Hunter",
			Verify: "cursor",
			Target: ")",
			Content: []string{
				"Use a( to target around the parentheses",
				"",
				"(hello)★",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "inner_bracket_hunter",
			Name:   "Inner Bracket Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Use i[ to target inside the brackets",
				"",
				"[hello★]",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "around_bracket_hunter",
			Name:   "Around Bracket Hunter",
			Verify: "cursor",
			Target: "]",
			Content: []string{
				"Use a[ to target around the brackets",
				"",
				"[hello]★",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "inner_quote_hunter",
			Name:   "Inner Quote Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Use i\" to target inside the quotes",
				"",
				"x\"magnificent★\"",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "around_quote_hunter",
			Name:   "Around Quote Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Use a\" to target around the quotes",
				"",
				"x\"magnificent\"★",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "paragraph_hunter",
			Name:   "Paragraph Hunter",
			Verify: "cursor",
			Target: "Z",
			Content: []string{
				"Use { and } to jump between paragraphs",
				"",
				"first paragraph",
				"",
				"second paragraph",
				"",
				"third Z",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "match_hunter",
			Name:   "Match Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Use % to jump to the matching delimiter",
				"",
				"[         ]★",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "delete_character_hunter",
			Name:   "Delete Character Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Use x to delete the extra letter",
				"",
				"helllo",
			},
			Result: []string{
				"Use x to delete the extra letter",
				"",
				"hello",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "replace_character_hunter",
			Name:   "Replace Character Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Use r to replace the wrong letter",
				"",
				"hallo",
			},
			Result: []string{
				"Use r to replace the wrong letter",
				"",
				"hello",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "toggle_case_hunter",
			Name:   "Toggle Case Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Use ~ to toggle the case of each letter",
				"",
				"HELLO",
			},
			Result: []string{
				"Use ~ to toggle the case of each letter",
				"",
				"hello",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "delete_word_hunter",
			Name:   "Delete Word Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Use dw to delete the middle word",
				"",
				"alpha bravo charlie",
			},
			Result: []string{
				"Use dw to delete the middle word",
				"",
				"alpha charlie",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "change_word_hunter",
			Name:   "Change Word Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Use ciw to change the word",
				"",
				"foo",
			},
			Result: []string{
				"Use ciw to change the word",
				"",
				"bar",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "utf8_cursor_hunter",
			Name:   "UTF-8 Cursor Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Use h to move past multi-byte characters to the star ★",
				"",
				"α β γ ★",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "delete_line_hunter",
			Name:   "Delete Line Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Use dd to delete the middle line",
				"",
				"keep",
				"remove",
				"keep",
			},
			Result: []string{
				"Use dd to delete the middle line",
				"",
				"keep",
				"keep",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "delete_to_end_hunter",
			Name:   "Delete To End Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Use d$ to delete from cursor to end of line",
				"",
				"keep this text remove_this_part",
			},
			Result: []string{
				"Use d$ to delete from cursor to end of line",
				"",
				"keep this text",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "delete_inner_word_hunter",
			Name:   "Delete Inner Word Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Use diw to delete inside the middle word",
				"",
				"keep remove keep",
			},
			Result: []string{
				"Use diw to delete inside the middle word",
				"",
				"keep  keep",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "delete_around_word_hunter",
			Name:   "Delete Around Word Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Use daw to delete around the middle word",
				"",
				"keep remove keep",
			},
			Result: []string{
				"Use daw to delete around the middle word",
				"",
				"keep keep",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "delete_inner_paren_hunter",
			Name:   "Delete Inner Paren Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Use di( to delete inside parentheses",
				"",
				"func(remove)",
			},
			Result: []string{
				"Use di( to delete inside parentheses",
				"",
				"func()",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "delete_around_paren_hunter",
			Name:   "Delete Around Paren Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Use da( to delete around parentheses",
				"",
				"func(remove)",
			},
			Result: []string{
				"Use da( to delete around parentheses",
				"",
				"func",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "delete_inner_quote_hunter",
			Name:   "Delete Inner Quote Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Use di\" to delete inside quotes",
				"",
				"\"remove\"",
			},
			Result: []string{
				"Use di\" to delete inside quotes",
				"",
				"\"\"",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "delete_around_quote_hunter",
			Name:   "Delete Around Quote Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Use da\" to delete around quotes",
				"",
				"\"remove\"",
			},
			Result: []string{
				"Use da\" to delete around quotes",
				"",
				"",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "change_inner_word_hunter",
			Name:   "Change Inner Word Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Use ciw to change the first word",
				"",
				"goodbye world",
			},
			Result: []string{
				"Use ciw to change the first word",
				"",
				"hello world",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "change_inner_paren_hunter",
			Name:   "Change Inner Paren Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Use ci( to change inside parentheses",
				"",
				"func(remove)",
			},
			Result: []string{
				"Use ci( to change inside parentheses",
				"",
				"func(hello)",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "change_inner_quote_hunter",
			Name:   "Change Inner Quote Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Use ci\" to change inside quotes",
				"",
				"\"remove\"",
			},
			Result: []string{
				"Use ci\" to change inside quotes",
				"",
				"\"hello\"",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "yank_line_hunter",
			Name:   "Unnamed Register Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Use yy to yank, then p to paste",
				"",
				"copy me",
			},
			Result: []string{
				"Use yy to yank, then p to paste",
				"",
				"copy me",
				"copy me",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "named_register_hunter",
			Name:   "Named Register Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Use \"ayy to store, then \"ap to retrieve",
				"",
				"copy me",
			},
			Result: []string{
				"Use \"ayy to store, then \"ap to retrieve",
				"",
				"copy me",
				"copy me",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "word_register_hunter",
			Name:   "Word Register Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Use \"ayw to store a word, then \"ap to paste it",
				"",
				"alpha beta",
			},
			Result: []string{
				"Use \"ayw to store a word, then \"ap to paste it",
				"",
				"alpha beta alpha",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "register_replace_hunter",
			Name:   "Register Replace Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Use \"ayy to store 'correct', then \"ap to replace 'wrong'",
				"",
				"correct",
				"wrong",
			},
			Result: []string{
				"Use \"ayy to store 'correct', then \"ap to replace 'wrong'",
				"",
				"correct",
				"correct",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "register_duplicate_hunter",
			Name:   "Register Duplicate Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Use \"ayy to store 'foo', then \"ap to paste below 'bar'",
				"",
				"foo",
				"bar",
			},
			Result: []string{
				"Use \"ayy to store 'foo', then \"ap to paste below 'bar'",
				"",
				"foo",
				"bar",
				"foo",
			},
			Layer: "Tutorial",
		},
		{
			ID:     "find_diw_combo",
			Name:   "Find + Delete Word",
			Verify: "composite",
			Content: []string{
				"Use f then a letter, followed by diw.",
				"",
				"keep delete keep",
			},
			Result: []string{
				"Use f then a letter, followed by diw.",
				"",
				"keep  keep",
			},
			Layer:      "Training",
			Evaluation: &challenge.Evaluation{MaxMoves: 8},
		},
		{
			ID:     "find_daw_combo",
			Name:   "Find + Delete Around",
			Verify: "composite",
			Content: []string{
				"Delete around the word using f<char> and daw",
				"",
				"keep delete keep",
			},
			Result: []string{
				"Delete around the word using f<char> and daw",
				"",
				"keep keep",
			},
			Layer:      "Training",
			Evaluation: &challenge.Evaluation{MaxMoves: 8},
		},
		{
			ID:     "find_di_paren_combo",
			Name:   "Find + Delete Inside",
			Verify: "composite",
			Content: []string{
				"Delete inside parentheses using f<char> and di(",
				"",
				"func(remove)",
			},
			Result: []string{
				"Delete inside parentheses using f<char> and di(",
				"",
				"func()",
			},
			Layer:      "Training",
			Evaluation: &challenge.Evaluation{MaxMoves: 8},
		},
		{
			ID:     "find_ca_quote_combo",
			Name:   "Find + Change Around",
			Verify: "composite",
			Content: []string{
				"Change text inside quotes using f<char> and ca\"",
				"",
				"\"remove\"",
			},
			Result: []string{
				"Change text inside quotes using f<char> and ca\"",
				"",
				"hello",
			},
			Layer:      "Training",
			Evaluation: &challenge.Evaluation{MaxMoves: 10},
		},
		{
			ID:     "find_ciw_combo",
			Name:   "Find + Change Word",
			Verify: "composite",
			Content: []string{
				"Change a word using f<char> and ciw",
				"",
				"keep delete keep",
			},
			Result: []string{
				"Change a word using f<char> and ciw",
				"",
				"keep hello keep",
			},
			Layer:      "Training",
			Evaluation: &challenge.Evaluation{MaxMoves: 10},
		},
		{
			ID:     "dw_dot_combo",
			Name:   "Delete + Repeat",
			Verify: "composite",
			Content: []string{
				"Delete multiple words using dw and .",
				"",
				"one two three four",
			},
			Result: []string{
				"Delete multiple words using dw and .",
				"",
				"one four",
			},
			Layer:      "Training",
			Evaluation: &challenge.Evaluation{MaxMoves: 8},
		},
		{
			ID:     "ciw_dot_combo",
			Name:   "Change + Repeat",
			Verify: "composite",
			Content: []string{
				"Change two words using ciw and repeat with .",
				"",
				"one two three",
			},
			Result: []string{
				"Change two words using ciw and repeat with .",
				"",
				"hello hello three",
			},
			Layer:      "Training",
			Evaluation: &challenge.Evaluation{MaxMoves: 12},
		},
		{
			ID:     "yank_paste_combo",
			Name:   "Yank + Paste",
			Verify: "composite",
			Content: []string{
				"Duplicate a line below using yy and p",
				"",
				"alpha",
				"beta",
			},
			Result: []string{
				"Duplicate a line below using yy and p",
				"",
				"alpha",
				"beta",
				"alpha",
			},
			Layer:      "Training",
			Evaluation: &challenge.Evaluation{MaxMoves: 8},
		},
		{
			ID:     "dd_paste_combo",
			Name:   "Cut + Paste",
			Verify: "composite",
			Content: []string{
				"Move a line to the end using dd and p",
				"",
				"one",
				"TWO",
				"three",
			},
			Result: []string{
				"Move a line to the end using dd and p",
				"",
				"one",
				"three",
				"TWO",
			},
			Layer:      "Training",
			Evaluation: &challenge.Evaluation{MaxMoves: 8},
		},
		{
			ID:     "dd_paste_before_combo",
			Name:   "Cut + Paste Before",
			Verify: "composite",
			Content: []string{
				"Swap two lines using dd and P",
				"",
				"first",
				"second",
			},
			Result: []string{
				"Swap two lines using dd and P",
				"",
				"second",
				"first",
			},
			Layer:      "Training",
			Evaluation: &challenge.Evaluation{MaxMoves: 8},
		},
		// Trial
		{
			ID:     "trial_find_delete",
			Name:   "Find + Delete Trial",
			Verify: "composite",
			Content: []string{
				"Remove the third word.",
				"",
				"apple banana cherry date",
			},
			Result: []string{
				"Remove the third word.",
				"",
				"apple banana date",
			},
			Layer:      "Trial",
			Evaluation: &challenge.Evaluation{MaxMoves: 6},
		},
		{
			ID:     "trial_find_change",
			Name:   "Find + Change Trial",
			Verify: "composite",
			Content: []string{
				"Replace the value with DONE.",
				"",
				`status = "pending"`,
			},
			Result: []string{
				"Replace the value with DONE.",
				"",
				`status = "DONE"`,
			},
			Layer:      "Trial",
			Evaluation: &challenge.Evaluation{MaxMoves: 8},
		},
		{
			ID:     "trial_dot_repeat",
			Name:   "Dot Repeat Trial",
			Verify: "composite",
			Content: []string{
				"Remove every occurrence of the.",
				"",
				"the fox and the dog and the bird",
			},
			Result: []string{
				"Remove every occurrence of the.",
				"",
				"fox and dog and bird",
			},
			Layer:      "Trial",
			Evaluation: &challenge.Evaluation{MaxMoves: 12},
		},
		{
			ID:     "trial_delete_choice",
			Name:   "Delete Choice Trial",
			Verify: "composite",
			Content: []string{
				"Remove the bracketed content.",
				"",
				"keep [remove] keep",
			},
			Result: []string{
				"Remove the bracketed content.",
				"",
				"keep  keep",
			},
			Layer:      "Trial",
			Evaluation: &challenge.Evaluation{MaxMoves: 6},
		},
		{
			ID:     "trial_repeat_choice",
			Name:   "Repeat Choice Trial",
			Verify: "composite",
			Content: []string{
				"Normalize all values to done.",
				"",
				"item = alpha",
				"item = beta",
				"item = gamma",
			},
			Result: []string{
				"Normalize all values to done.",
				"",
				"item = done",
				"item = done",
				"item = done",
			},
			Layer:      "Trial",
			Evaluation: &challenge.Evaluation{MaxMoves: 12},
		},
	}
}

func IDs() []string {
	all := All()
	ids := make([]string, 0, len(all))
	for _, c := range all {
		ids = append(ids, c.ID)
	}
	return ids
}

func Exists(id string) bool {
	for _, c := range All() {
		if c.ID == id {
			return true
		}
	}
	return false
}
