package content

import "github.com/divijg19/Praxis/internal/challenge"

func All() []challenge.Challenge {
	return []challenge.Challenge{
		{
			ID:     "motion_rush",
			Name:   "Motion Rush",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Move your cursor to the star ★",
			},
		},
		{
			ID:     "grid_rush",
			Name:   "Grid Rush",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				". . . . .",
				". . . ★ .",
				". . . . .",
			},
		},
		{
			ID:     "find_hunter",
			Name:   "Find Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"find motions are fast",
				"",
				"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa★",
			},
		},
		{
			ID:     "word_hunter",
			Name:   "Word Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"word motions are fast",
				"",
				"alpha beta gamma delta epsilon ★",
			},
		},
		{
			ID:     "symbol_hunter",
			Name:   "Symbol Hunter",
			Verify: "cursor",
			Target: "@",
			Content: []string{
				"find the target symbol",
				"",
				".......................@",
			},
		},
		{
			ID:     "line_hunter",
			Name:   "Line Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Move to the line with the star",
				"",
				"line one",
				"line two",
				"line three",
				"line four",
				"line five",
				"★ line six",
			},
		},
		{
			ID:     "paren_hunter",
			Name:   "Paren Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Jump to the matching paren",
				"",
				"(                         )★",
			},
		},
		{
			ID:     "sentence_hunter",
			Name:   "Sentence Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Jump between sentences",
				"",
				"First sentence ends here.",
				"Second. Third.",
				"★ Fourth. Fifth.",
			},
		},
		{
			ID:     "slash_hunter",
			Name:   "Slash Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Search forward to find the target",
				"",
				"alpha  bravo  charlie  delta  echo  foxtrot  golf  ★",
			},
		},
		{
			ID:     "question_hunter",
			Name:   "Question Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Search backward to find the target",
				"",
				"line one",
				"line two",
				"line three",
				"line four",
				"line five",
				"line six",
				"line seven",
				"line eight",
				"line nine",
				"line ten",
				"line eleven",
				"line twelve",
				"line thirteen",
				"line fourteen",
				"line fifteen",
				"line sixteen",
				"★ line seventeen",
				"line eighteen",
			},
		},
		{
			ID:     "repeat_hunter",
			Name:   "Repeat Hunter",
			Verify: "cursor",
			Target: "@",
			Content: []string{
				"Search for ★, then repeat to find @",
				"",
				"★  ★  ★  ★  ★  ★  ★  ★  @",
			},
		},
		{
			ID:     "inner_paren_hunter",
			Name:   "Inner Paren Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Select inside the parentheses",
				"",
				"(hello★)",
			},
		},
		{
			ID:     "around_paren_hunter",
			Name:   "Around Paren Hunter",
			Verify: "cursor",
			Target: ")",
			Content: []string{
				"Select around the parentheses",
				"",
				"(hello)★",
			},
		},
		{
			ID:     "inner_bracket_hunter",
			Name:   "Inner Bracket Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Select inside the brackets",
				"",
				"[hello★]",
			},
		},
		{
			ID:     "around_bracket_hunter",
			Name:   "Around Bracket Hunter",
			Verify: "cursor",
			Target: "]",
			Content: []string{
				"Select around the brackets",
				"",
				"[hello]★",
			},
		},
		{
			ID:     "inner_quote_hunter",
			Name:   "Inner Quote Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Select inside the quotes",
				"",
				"x\"magnificent★\"",
			},
		},
		{
			ID:     "around_quote_hunter",
			Name:   "Around Quote Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Select around the quotes",
				"",
				"x\"magnificent\"★",
			},
		},
		{
			ID:     "paragraph_hunter",
			Name:   "Paragraph Hunter",
			Verify: "cursor",
			Target: "Z",
			Content: []string{
				"Jump to the last paragraph",
				"",
				"first paragraph",
				"",
				"second paragraph",
				"",
				"third Z",
			},
		},
		{
			ID:     "match_hunter",
			Name:   "Match Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Jump to the matching delimiter",
				"",
				"[         ]★",
			},
		},
		{
			ID:     "delete_character_hunter",
			Name:   "Delete Character Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Delete the extra letter",
				"",
				"helllo",
			},
			Result: []string{
				"Delete the extra letter",
				"",
				"hello",
			},
		},
		{
			ID:     "replace_character_hunter",
			Name:   "Replace Character Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Replace the wrong letter",
				"",
				"hallo",
			},
			Result: []string{
				"Replace the wrong letter",
				"",
				"hello",
			},
		},
		{
			ID:     "toggle_case_hunter",
			Name:   "Toggle Case Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Toggle the case of each letter",
				"",
				"HELLO",
			},
			Result: []string{
				"Toggle the case of each letter",
				"",
				"hello",
			},
		},
		{
			ID:     "delete_word_hunter",
			Name:   "Delete Word Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Delete the middle word",
				"",
				"keep lose keep",
			},
			Result: []string{
				"Delete the middle word",
				"",
				"keep  keep",
			},
		},
		{
			ID:     "change_word_hunter",
			Name:   "Change Word Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Change the word using ciw",
				"",
				"foo",
			},
			Result: []string{
				"Change the word using ciw",
				"",
				"bar",
			},
		},
		{
			ID:     "utf8_cursor_hunter",
			Name:   "UTF-8 Cursor Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Navigate past multi-byte characters to the star",
				"",
				"α β γ ★",
			},
		},
		{
			ID:     "delete_line_hunter",
			Name:   "Delete Line Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Delete the middle line",
				"",
				"keep",
				"remove",
				"keep",
			},
			Result: []string{
				"Delete the middle line",
				"",
				"keep",
				"keep",
			},
		},
		{
			ID:     "delete_to_end_hunter",
			Name:   "Delete To End Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Delete from cursor to end of line",
				"",
				"keep this text remove_this_part",
			},
			Result: []string{
				"Delete from cursor to end of line",
				"",
				"keep this text",
			},
		},
		{
			ID:     "delete_inner_word_hunter",
			Name:   "Delete Inner Word Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Delete inside the middle word",
				"",
				"keep remove keep",
			},
			Result: []string{
				"Delete inside the middle word",
				"",
				"keep  keep",
			},
		},
		{
			ID:     "delete_around_word_hunter",
			Name:   "Delete Around Word Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Delete around the middle word",
				"",
				"keep remove keep",
			},
			Result: []string{
				"Delete around the middle word",
				"",
				"keep keep",
			},
		},
		{
			ID:     "delete_inner_paren_hunter",
			Name:   "Delete Inner Paren Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Delete inside parentheses",
				"",
				"func(remove)",
			},
			Result: []string{
				"Delete inside parentheses",
				"",
				"func()",
			},
		},
		{
			ID:     "delete_around_paren_hunter",
			Name:   "Delete Around Paren Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Delete around parentheses",
				"",
				"func(remove)",
			},
			Result: []string{
				"Delete around parentheses",
				"",
				"func",
			},
		},
		{
			ID:     "delete_inner_quote_hunter",
			Name:   "Delete Inner Quote Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Delete inside quotes",
				"",
				"\"remove\"",
			},
			Result: []string{
				"Delete inside quotes",
				"",
				"\"\"",
			},
		},
		{
			ID:     "delete_around_quote_hunter",
			Name:   "Delete Around Quote Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Delete around quotes",
				"",
				"\"remove\"",
			},
			Result: []string{
				"Delete around quotes",
				"",
				"",
			},
		},
		{
			ID:     "change_inner_word_hunter",
			Name:   "Change Inner Word Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Change the first word",
				"",
				"goodbye world",
			},
			Result: []string{
				"Change the first word",
				"",
				"hello world",
			},
		},
		{
			ID:     "change_inner_paren_hunter",
			Name:   "Change Inner Paren Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Change inside parentheses",
				"",
				"func(remove)",
			},
			Result: []string{
				"Change inside parentheses",
				"",
				"func(hello)",
			},
		},
		{
			ID:     "change_inner_quote_hunter",
			Name:   "Change Inner Quote Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Change inside quotes",
				"",
				"\"remove\"",
			},
			Result: []string{
				"Change inside quotes",
				"",
				"\"hello\"",
			},
		},
		{
			ID:     "yank_line_hunter",
			Name:   "Unnamed Register Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Every yank enters a register. Yank and paste to see.",
				"",
				"copy me",
			},
			Result: []string{
				"Every yank enters a register. Yank and paste to see.",
				"",
				"copy me",
				"copy me",
			},
		},
		{
			ID:     "named_register_hunter",
			Name:   "Named Register Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Store and retrieve with register a",
				"",
				"copy me",
			},
			Result: []string{
				"Store and retrieve with register a",
				"",
				"copy me",
				"copy me",
			},
		},
		{
			ID:     "word_register_hunter",
			Name:   "Word Register Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Store a word in register a, then append it",
				"",
				"alpha beta",
			},
			Result: []string{
				"Store a word in register a, then append it",
				"",
				"alpha beta alpha",
			},
		},
		{
			ID:     "register_replace_hunter",
			Name:   "Register Replace Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Store 'correct' in register a, then replace 'wrong'",
				"",
				"correct",
				"wrong",
			},
			Result: []string{
				"Store 'correct' in register a, then replace 'wrong'",
				"",
				"correct",
				"correct",
			},
		},
		{
			ID:     "register_duplicate_hunter",
			Name:   "Register Duplicate Hunter",
			Verify: "buffer",
			Target: "",
			Content: []string{
				"Duplicate 'foo' below 'bar' using register a",
				"",
				"foo",
				"bar",
			},
			Result: []string{
				"Duplicate 'foo' below 'bar' using register a",
				"",
				"foo",
				"bar",
				"foo",
			},
		},
	}
}
