package content

import "github.com/divijg19/Praxis/internal/challenge"

func All() []challenge.Challenge {
	return []challenge.Challenge{
		{
			ID:     "motion_rush",
			Name:   "Motion Rush",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Move your cursor to the star ★",
			},
		},
		{
			ID:     "grid_rush",
			Name:   "Grid Rush",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				". . . . .",
				". . . ★ .",
				". . . . .",
			},
		},
		{
			ID:     "find_hunter",
			Name:   "Find Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"find motions are fast",
				"",
				"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa★",
			},
		},
		{
			ID:     "word_hunter",
			Name:   "Word Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"word motions are fast",
				"",
				"alpha beta gamma delta epsilon ★",
			},
		},
		{
			ID:     "symbol_hunter",
			Name:   "Symbol Hunter",
			Verify: "cursor",
			Target: "@",
			Content: []string{
				"find the target symbol",
				"",
				".......................@",
			},
		},
		{
			ID:     "line_hunter",
			Name:   "Line Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Move to the line with the star",
				"",
				"line one",
				"line two",
				"line three",
				"line four",
				"line five",
				"★ line six",
			},
		},
		{
			ID:     "paren_hunter",
			Name:   "Paren Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Jump to the matching paren",
				"",
				"(                         )★",
			},
		},
		{
			ID:     "sentence_hunter",
			Name:   "Sentence Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Jump between sentences",
				"",
				"First sentence ends here.",
				"Second. Third.",
				"★ Fourth. Fifth.",
			},
		},
		{
			ID:     "slash_hunter",
			Name:   "Slash Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Search forward to find the target",
				"",
				"alpha  bravo  charlie  delta  echo  foxtrot  golf  ★",
			},
		},
		{
			ID:     "question_hunter",
			Name:   "Question Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Search backward to find the target",
				"",
				"line one",
				"line two",
				"line three",
				"line four",
				"line five",
				"line six",
				"line seven",
				"line eight",
				"line nine",
				"line ten",
				"line eleven",
				"line twelve",
				"line thirteen",
				"line fourteen",
				"line fifteen",
				"line sixteen",
				"★ line seventeen",
				"line eighteen",
			},
		},
		{
			ID:     "repeat_hunter",
			Name:   "Repeat Hunter",
			Verify: "cursor",
			Target: "@",
			Content: []string{
				"Search for ★, then repeat to find @",
				"",
				"★  ★  ★  ★  ★  ★  ★  ★  @",
			},
		},
		{
			ID:     "inner_paren_hunter",
			Name:   "Inner Paren Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Select inside the parentheses",
				"",
				"(hello★)",
			},
		},
		{
			ID:     "around_paren_hunter",
			Name:   "Around Paren Hunter",
			Verify: "cursor",
			Target: ")",
			Content: []string{
				"Select around the parentheses",
				"",
				"(hello)★",
			},
		},
		{
			ID:     "inner_bracket_hunter",
			Name:   "Inner Bracket Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Select inside the brackets",
				"",
				"[hello★]",
			},
		},
		{
			ID:     "around_bracket_hunter",
			Name:   "Around Bracket Hunter",
			Verify: "cursor",
			Target: "]",
			Content: []string{
				"Select around the brackets",
				"",
				"[hello]★",
			},
		},
		{
			ID:     "inner_quote_hunter",
			Name:   "Inner Quote Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Select inside the quotes",
				"",
				"x\"magnificent★\"",
			},
		},
		{
			ID:     "around_quote_hunter",
			Name:   "Around Quote Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Select around the quotes",
				"",
				"x\"magnificent\"★",
			},
		},
		{
			ID:     "paragraph_hunter",
			Name:   "Paragraph Hunter",
			Verify: "cursor",
			Target: "Z",
			Content: []string{
				"Jump to the last paragraph",
				"",
				"first paragraph",
				"",
				"second paragraph",
				"",
				"third Z",
			},
		},
		{
			ID:     "match_hunter",
			Name:   "Match Hunter",
			Verify: "cursor",
			Target: "★",
			Content: []string{
				"Jump to the matching delimiter",
				"",
				"[         ]★",
			},
		},
	}
}
